[conn]
host = ""
port = 3233
proto = "simple" # avaliable simple - SimpleProto , tcd8 - TCD8

[saveloader]
type = 'json' # avaliable mongo, json
connection = {host  = '127.0.0.1', port = 27017, user = '', password = '', auth = false}
db = {database = 'fsdb', collection = 'fsusers'}
storage = 'storage'

